@startuml
title DDD-дизайн для системы "Умный дом"

package "Домен: Управление пользователями" {
  package "Поддомен: Регистрация и авторизация" {
    [Контекст: Регистрация]
    [Контекст: Авторизация]
  }
  package "Поддомен: Управление учетными записями пользователей" {
    [Контекст: Управление профилями]
    [Контекст: Управление доступом]
  }
}


package "Домен: Управление устройствами" {
  package "Поддомен: Управление подключением устройств" {
    [Контекст: Регистрация устройств]
    [Контекст: Управление подключениями]
  }

  package "Поддомен: Работы со сценариями" {
    [Контекст: Создание сценариев]
    [Контекст: Удаление сценариев]
    [Контекст: Выполнение сценариев]
    [Контекст: Отправка уведомлений]
  }

  package "Поддомен: Работы с расписанием" {
    [Контекст: Создание расписания]
    [Контекст: Удаление расписания]
    [Контекст: Запуск задач по расписанию]
  }

  package "Поддомен: Взаимодействие с устройствами" {
    [Контекст: Отправка команд]
    [Контекст: Получение статусов]
  }
}

package "Домен: Телеметрия" {
  package "Поддомен: Сбор данных" {
    [Контекст: Получение телеметрии]
  }
  package "Поддомен: Хранение исторических данных" {
    [Контекст: Хранение телеметрии]
  }
  package "Поддомен: Анализ телеметрии" {
    [Контекст: Аналитика данных]
  }
}

@enduml
